name: Build cross-platform executables

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install build tools
        run: |
          pip install pyinstaller pygame

      - name: Build Windows EXE
        run: |
          python -m PyInstaller --onefile --windowed --name Bingo-Kids display.py

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Windows EXE
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/Bingo-Kids.exe
          asset_name: Bingo-Kids-windows.exe
          asset_content_type: application/vnd.microsoft.portable-executable


  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install build tools
        run: |
          pip install pyinstaller pygame

      - name: Build macOS binary
        run: |
          python3 -m PyInstaller --onefile --windowed --name Bingo-Kids display.py

      - name: Create Release
        id: create_release_macos
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload macOS binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release_macos.outputs.upload_url }}
          asset_path: dist/Bingo-Kids
          asset_name: Bingo-Kids-macos
          asset_content_type: application/octet-stream
